version: '3.6'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/html

  db:
    image: mysql
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MyMobileShop_dev
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer-mysql
    restart: always
    ports:
      - 8080:8080
